components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      scheme: bearer
      bearerFormat: JWT
      in: header
      name: Authorization

tags:
  - name: Autenticacion
    description: Endpoints relacionados con las autenticaciones
  - name: Carreras
    description: Endpoints relacionados con carreras
  - name: Usuarios
    description: Endpoints relacionados con usuarios
  - name: Materias
    description: Endpoints relacionados con materias
  - name: Inscripción
    description: Endpoints relacionados con las inscripciones

paths:
  /auth/singup:
    post:
      summary: Autenticación de usuario
      tags:
        - Autenticacion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dni:
                  type: string
                nombre:
                  type: string
                password:
                  type: string
                role:             
                  type: string    
              example:
                dni: 44258120
                nombre: Walter White
                email: walterwhite@albuquerque.com
                picture: https://avatars.githubusercontent.com/u/84170516
                password: abcdef
                role: profesor

      responses:
        201:
          description: Usuario creado exitosamente
        500:
          description: Error interno al generar usuario

  /auth/singin:
    post:
      summary: Autenticación de usuario
      tags:
        - Autenticacion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dni:
                  type: string
                password:
                  type: string
              example:
                dni: 44258120
                password: abcdef
      responses:
        200:
          description: Autenticación exitosa
        401:
          description: Credenciales incorrectas
        404:
          description: Usuario no encontrado
        500:
          description: Error al generar token

  /carreras:
    get:
      summary: Obtiene todas las carreras
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: Indice de la paginacion
      tags:
        - Carreras
      responses:
        '200':
          description: Lista de carreras obtenida exitosamente
        '500':
          description: Error al obtener las carreras

    post:
      summary: Crea una nueva carrera
      tags:
        - Carreras
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                descripcion:
                  type: string
                duracion:
                  type: string
                titulo:
                  type: string
              example:
                nombre: Licenciatura en Informática
                descripcion: Descripcion de la carrera
                duracion: 5 Años
                titulo: Licenciado/a en Informática

      security:
        - BearerAuth: []
      responses:
        '200':
          description: Carrera creada exitosamente
        '500':
          description: Error al crear la carrera

  /carreras/{id}:
    get:
      summary: Obtiene una carrera por ID
      tags:
        - Carreras
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la carrera a buscar
      responses:
        '200':
          description: Carrera encontrada exitosamente
        '404':
          description: Carrera no encontrada
        '500':
          description: Error al buscar la carrera
    
    put:
      summary: Actualizar una carrera por ID
      tags:
        - Carreras

    delete:
      summary: Elimina una carrera por ID
      tags:
        - Carreras
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la carrera a eliminar
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Carrera eliminada exitosamente
        '404':
          description: Carrera no encontrada
        '500':
          description: Error al buscar o eliminar la carrera

  /usuarios:
    get:
      summary: Obtiene todos los usuarios
      tags:
        - Usuarios
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista de usuarios obtenida exitosamente
        '500':
          description: Error al obtener los usuarios

  /usuarios/{id}:
    get:
      summary: Obtiene un usuario por ID
      tags:
        - Usuarios
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del usuario a buscar
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Usuario encontrado exitosamente
        '404':
          description: Usuario no encontrado
        '500':
          description: Error al buscar el usuario

    delete:
      summary: Elimina un usuario por ID
      tags:
        - Usuarios
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID del usuario a eliminar
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Usuario eliminado exitosamente
        '404':
          description: Usuario no encontrado
        '500':
          description: Error al buscar o eliminar el usuario
    put:
        summary: Actualiza un usuario por ID
        tags:
          - Usuarios
        parameters:
          - in: path
            name: id
            schema:
              type: string
            required: true
            description: ID de la materia a buscar
        responses:
          '200':
            description: Materia encontrada exitosamente
          '404':
            description: Materia no encontrada
          '500':
            description: Error al buscar la materia
  /materias:
    get:
      summary: Obtiene todas las materias
      tags:
        - Materias
      responses:
        '200':
          description: Lista de materias obtenida exitosamente
        '500':
          description: Error al obtener las materias

    post:
      summary: Crea una nueva materia
      tags:
        - Materias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                carrera_id:
                  type: string
                profesor_id:            
                  type: integer         
              example:
                name: Nombre de la materia
                carrera_id: ID de la carrera
                profesor_id: 44569863   
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Materia creada exitosamente
        '500':
          description: Error al crear la materia

  /materias/{id}:
    get:
      summary: Obtiene una materia por ID
      tags:
        - Materias
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la materia a buscar
      responses:
        '200':
          description: Materia encontrada exitosamente
        '404':
          description: Materia no encontrada
        '500':
          description: Error al buscar la materia
    put:
      summary: Actualiza una materia por ID
      tags:
        - Materias
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la materia a buscar
      responses:
        '200':
          description: Materia encontrada exitosamente
        '404':
          description: Materia no encontrada
        '500':
          description: Error al buscar la materia

    delete:
      summary: Elimina una materia por ID
      tags:
        - Materias
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID de la materia a eliminar
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Materia eliminada exitosamente
        '404':
          description: Materia no encontrada
        '500':
          description: Error al buscar o eliminar la materia

  /inscripciones:
    post:
      summary: Realiza la inscripción de un usuario a una materia
      tags:
        - Inscripción
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: materia_id
          schema:
            type: string
          required: true
          description: ID de la materia a la que se desea inscribir
        - in: path
          name: usuario_id
          schema:
            type: string
          required: true
          description: ID del usuario que desea inscribirse
      responses:
        '200':
          description: Inscripción exitosa
        '404':
          description: Usuario o materia no encontrados
        '500':
          description: Error al intentar realizar la inscripción
    get:
      summary: Realiza la consulta de todas las inscripciones en el sistema
      tags:
        - Inscripción
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: usuario_id
          schema:
            type: string
          required: true
          description: ID del usuario al que desea buscar sus carreras inscriptas
      responses:
        '200':
          description: Carreras encontradas exitosamente
        '404':
          description: Carreras no encontradas
        '500':
          description: Error al buscar las carreras

    delete:
      summary: Elimina una inscripcion dada un ID
      tags:
        - Inscripción
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: usuario_id
          schema:
            type: string
          required: true
          description: ID del usuario al que desea buscar sus carreras inscriptas
      responses:
        '200':
          description: Carreras encontradas exitosamente
        '404':
          description: Carreras no encontradas
        '500':
          description: Error al buscar las carreras

